name: CI
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

defaults:
  run:
    working-directory: 'stonesoupkitchen.banner'

permissions: read-all

jobs:
  analyze:
    name: Analyze
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: 'stonesoupkitchen.banner'

      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pipenv wheel
          pipenv install --dev

      - name: Lint
        run: |
          make lint

  test:
    name: Test
    needs: [Analyze]
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - 'debian:10'
          - 'debian:11'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: 'stonesoupkitchen.banner'

      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pipenv wheel
          pipenv install --dev

      - name: Run Molecule tests
        run: make test
        env:
          ANSIBLE_FORCE_COLOR: '1'
          PY_COLORS: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

  release:
    name: Release
    permissions:
      contents: read
    needs: [Analyze, Test]
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    container: ghcr.io/stonesoupkitchen/github-publisher:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: 'stonesoupkitchen.banner'
          fetch-depth: 0
          token: ${{ secrets.SSKBOT_RELEASE_TOKEN }}

      - name: Release
        env:
          GIT_USER: stonesoupkitchenbot
          GIT_EMAIL: 80210448+stonesoupkitchenbot@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.SSKBOT_RELEASE_TOKEN }}
        run: create_release

  publish:
    name: Publish
    permissions:
      contents: read
    needs: [Analyze, Test, Release]
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: 'stonesoupkitchen.banner'

      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install ansible-base

      - name: Publish to Ansible Galaxy
        run: >
          ansible-galaxy role import
          --api-key ${{ secrets.GALAXY_API_KEY }}
          $(echo $GITHUB_REPOSITORY | cut -d/ -f1)
          $(echo $GITHUB_REPOSITORY | cut -d/ -f2)
